version: 2
jobs:
  build:
    macos:
      xcode: "11.5.0"

    steps:
      - checkout
      - run:
          name: Build and run tests
          command: xcodebuild -project Example/Sample/iZettleSDKSample.xcodeproj clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO